### PR TITLE
Issue #18 - Add an update Script.

### PR DESCRIPTION
**Pull request by tamarahills**

### CODE REVIEW

**Comment by tamarahills** [comment]
Russ, can you take a look at this?  I was not sure if I should put the restart of abigail-device in here or not.  I saw that you have that in the readme, but I don't see it in your bootstrap script.  I'm thinking you did not put it in here because you were thinking of the wifi startup race condition for first time?

**Comment by russnicoletti** [comment]
It's better if the update script doesn't restart the abigail device because the wifi setup script will do that when it detects a network connection, and the wife setup scripts runs at startup.

**Comment by russnicoletti** [comment]
Does the cron job redirect the output of the update script to a file? I think that's important to be able to check for errors.

**Review by russnicoletti — APPROVED** [review]
Does the cron job redirect the output of the update script to a file? I think it should so we can check for errors.

**Pull request merged**
